project-brewery
byrdfabian/project-brewery pull request #6
Opened 2020-08-26 23:37 UTC by BriF0890

add the Top 10 Breweries and add link to go to the website to each one.

2020-08-26 23:39 UTC, Vsmith408 approved these changes

2020-08-27 01:49 UTC, byrdfabian approved these changes

2020-08-29 14:13 UTC, BriF0890 commented
Added a Top 10 breweries html

2020-08-29 15:59 UTC, Vsmith408 requested changes

2020-08-29 15:59 UTC, Vsmith408 commented on top10.html
> +
wrap rows in container and center align cards

2020-08-29 17:19 UTC, merged